

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <style scoped>
         @font-face {
            font-family: 'clearviewhwy5-b';
            src: url('/public/fonts/ufonts.com_clearviewhwy-5-b-webfont.eot');
            src: url('/public/fonts/ufonts.com_clearviewhwy-5-b-webfont.eot?#iefix') format('embedded-opentype'), url('/public/fonts/ufonts.com_clearviewhwy-5-b-webfont.woff2') format('woff2'), url('/public/fonts/ufonts.com_clearviewhwy-5-b-webfont.woff') format('woff'), url('/public/fonts/ufonts.com_clearviewhwy-5-b-webfont.ttf') format('truetype'), url('/public/fonts/ufonts.com_clearviewhwy-5-b-webfont.svg#clearviewhwy5-b') format('svg');
            font-weight: normal;
            font-style: normal;
        }
       #navContainer {
            min-width: 80% !important;
        }

        .nav > li > a {
            font-family: 'clearviewhwy5-b', Calibri, Candara, Arial, sans-serif;
            font-size: 12px !important;
            padding: 15px 9px !important;
            font-weight: normal;
        }
        .navB {
            height:53px;
        }

        #navTitleLabel {
            font-family: 'clearviewhwy5-b', Calibri, Candara, Arial, sans-serif;
            font-size: 25px !important;
            text-decoration: underline;
            font-weight: 300 !important;
        }

        /* Generated by Font Squirrel (http://www.fontsquirrel.com) on March 10, 2015 */



       
    </style>
    <div id="navContainer" class="container" style="width: 100%;">
        <div class="row">
            <div class="col-xs-2" style="padding-right:0px;padding-top:10px;height: 57px;">
                
                <a class="navbar-brand pull-left" style="padding:0px;" href="#">
                    <img style="width: 60px;" class="pull-left" alt="Brand" src="/Images/mblx-logo.png" />

                </a>
                <h3 id="navTitleLabel" style="color: #fff;width:200px;margin-top:15px;">C.A.T.S.</h3>
            </div>
           <div 
            <div class="col-xs-10 col-md-9 navbar-right" style="padding-right:3pxpx;padding-left:15px;">
                <!--div class="row"-->


                <!--div class="row"-->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" data-aria-expanded="false" data-aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>
                <div id="navbar" class="navbar-collapse collapse " style="padding-top: 4px;">
                    <ul id="navTHings" class="nav navbar-nav">
                        <li id="homeNavButton" class="active"><a class=" navB btn btn-default btn-lg" role="button" href="/main.php"><span class=" glyphicon glyphicon-home"></span></a></li>
                        <li id="myBookingsNavButton"><a href="../main.php" class="navB">My Bookings</a>
                        </li>
                        <li id="customersNavButton" class="dropdown">
                            <a href="#" class="dropdown-toggle navB" data-toggle="dropdown">Customers <span class="caret pull-right" style="margin-top : 10%;"></span></a>
                            <ul class="dropdown-menu" role="menu">

                                <li class="divider"></li>

                                <li><a href="/pages/customer.php">Customers and Contacts</a>
                                </li>

                               <li><a href="/pages/contract.php">Customer Contracts</a>
                                </li>
                                <li><a href="/pages/commodities.php">Commodities</a>
                        </li>

                            </ul>
                        </li>
                        <li class="dropdown" id="bargesNavButton">
                            <a href="#" class="dropdown-toggle navB" data-toggle="dropdown">Barges <span class="caret pull-right" style = "margin-top : 12%;"></span></a>
                            <ul class="dropdown-menu" role="menu">

                                <li class="divider"></li>

                                <li><a href="/pages/barges.php">Barges</a>
                                </li>
                                <li><a href="/pages/bargeLines.php">Barge Lines</a>
                                </li>

                                <li><a href="/pages/bargeTrip.php">Barge Trip</a>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown" id="carrierNavButton">
                            <a href="#" class="dropdown-toggle navB" data-toggle="dropdown">Carrier <span class="caret pull-right" style = "margin-top : 12%;"></span></a>
                            <ul class="dropdown-menu" role="menu">

                                <li class="divider"></li>

                                <li><a href="/pages/carrierContracts.php">Carrier Contracts</a>
                                </li>
                                <li><a href="/pages/spotContractPage.php">Spot Contracts</a>
                                </li>
                                <li><a href="/pages/origin.php">Origins</a>
                                </li>
                                <li><a href="/pages/stevedores.php">Stevedores</a>
                                </li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle navB" data-toggle="dropdown">Destinations <span class="caret pull-right" style = "margin-top : 8%;"></span></a>
                            <ul class="dropdown-menu" role="menu">

                                <li class="divider"></li>

                                <li><a href="/pages/destination.php">Destination Page</a>
                                </li>
                                <li><a href="/pages/terminal.php">Terminal Page</a>
                                </li>
                                <li><a href="/pages/wharves.php">Wharves Page</a>
                                </li>
                            </ul>
                        </li>
                        
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle navB" data-toggle="dropdown">Reports <span class="caret pull-right" style = "margin-top : 12%;"></span></a>
                            <ul class="dropdown-menu" role="menu">

                                <li class="divider"></li>

                                <li><a href="/pages/bookingspage.php">Origin Schedule</a>
                                </li>
                                <li><a href="/Functions/exportData/getExportDataFile.php">Export Booking Data File</a>
                                </li>

                            </ul>
                        </li>

                     

                        <li id="newBookingNavButton"><a class="btn btn-primary btn-lg active" role="button" href="/pages/newbooking.php">New Booking</a></li>

                    </ul>
                    <!--ul class="nav navbar-nav navbar-right">
                    <li><button class="btn btn-danger" role="button">Save</button>
                    </li>
                    <li><button class="btn btn-success" role="button">Add</button>
                    </li>
                    
                </ul-->
                </div>
                <!--/.nav-collapse -->
                <!--/div-->
            </div>
        </div>
    </div>
</nav>
